### ISSUE TITLE
Solve security vulnerablilies from external packages

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/oe_geoutils#101]
https://github.com/OnroerendErfgoed/oe_geoutils/network/alerts

Colander and request need to be updated to the latest release. It's probably a good idea to update all packages to the latest release.

**Comment by Wim-De-Clercq** [comment]
pycountry is ook gepint:
19.7.15 en hoger heb ik niet genomen want (hoewel het wel installeert)
```
19.7.15 (2019-07-15)
    Drop support for Python 2.
```
En ook de vorige release 18.12.8:
```
18.12.8 (2018-12-08)

WARNING: This release contains a subtle but important API change that may break integrations!
```
Heeft code changes nodig, dus die doe sla ik voor dit ticket ook even over.
