### ISSUE TITLE
pycountry upgraden

### ISSUE THREAD

**Issue by Wim-De-Clercq** [OnroerendErfgoed/oe_geoutils#115]
Afhankelijk van python 2 support of niet kunnen we de laatste nieuwe of <19.7.15 gebruiken.

Maar hiervoor moeten we nakijken dat de API change van `18.12.8 (2018-12-08)` niet wordt gebruikt in de code.

> WARNING: This release contains a subtle but important API change that may break integrations!
> 
> Looking at #13416 I realized that I made a terrible API design choice with respect to how the get function should behave in Python. Probably under the influence of either too little or too much whiskey I went and implemented get so that it raises a KeyError instead of doing the Pythonic thing and returning None and allowing to customize the default. There was a bit of back-and-forth around this code in previous releases (specifically touching edge cases to have the Subdivision API behave “reasonably”, although there doesn’t seem to be one right way there.)
> 
> Anyway, when preparing this release and reviewing #13416 and the other related issues and changes from the past I noticed my mistake an decide to fix it going forward.
> 
> So, from now on get will behave as expected in Python and yes, this means you will have to update your integration code carefully now checking for None returns instead of expecting KeyErrors. This is work, but I think it’s worthwhile to uphold this convention within the Python community.
> 
>     Switch API from “get + KeyError” to ” get + default=None”. This is a subtle API-breaking change. Please update carefully. (#13416)
>     Update to iso-codes 4.1.

**Comment by claeyswo** [comment]
https://github.com/OnroerendErfgoed/oe_geoutils/blob/642f02ecb34c74d24fb55d514b0dbdc0d33a5ac3/oe_geoutils/validation/validators_address.py#L195
https://github.com/OnroerendErfgoed/oe_geoutils/blob/642f02ecb34c74d24fb55d514b0dbdc0d33a5ac3/oe_geoutils/validation/validators_location_elements.py#L191

KeyErrors vervangen door checks op None return
