### ISSUE TITLE
Validatie nummers aanpassen

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/oe_geoutils#123]
We krijgen momenteel zoiets binnen: Oostendelaan 205_109. We aanvaarden nu enkel alfanumerieke nummers. Ik dacht dat dat in inventaris correct geïmplementeerd zat. Indien niet gewoon ook _ en - toevoegen als geldige karakters.

**Comment by koenedaele** [comment]
Waar staat die 205_109 voor? Is die 109 een bis- of busnummer of zo? Dat had toch een andere schrijfwijze?

**Comment by claeyswo** [comment]
Geen flauw idee.

**Comment by Wim-De-Clercq** [comment]
Dus laat ik dan specifiek `\d+_\d+` toe als regex? gewone hyphens ook? (`-`). Of laten we nog meer toe?

**Comment by claeyswo** [comment]
Hoe zit dat bij de inventaris?

**Comment by Wim-De-Clercq** [comment]
```

**Comment by claeyswo** [comment]
Geen idee ook eigenlijk, ik zou hier dan ook gewoon de inventaris regels overnemen waarbij _ ook een geldige optie is ipv -.

**Comment by Wim-De-Clercq** [comment]
In housenum-be-r parser is die underscore een bis nummer btw. Kan ofwel met `/` of `_`
https://github.com/OnroerendErfgoed/housenum-be-r-parser/blob/4e9333c622e1dc9af1290f3147d8fe0f1146c586/housenumparser/element.py#L172
