### ISSUE TITLE
Huisnummer validatie

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/oe_geoutils#127]
Nog problemen, 65TER als nummer wordt ook niet aanvaard.

**Comment by Wim-De-Clercq** [comment]
dus eehm gewoon `\d.*` dan? xD

**Comment by claeyswo** [comment]
Awel, ik begin het ook te denken. Ik weet niet waar die funky nummers de laatste tijd allemaal vandaan komen.
