### ISSUE TITLE
Foutboodschap verkeerde geometrie aanpassen

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/oe_geoutils#56]
De melding  gewoon gaan aanpassen naar
>"Geometrie ligt niet binnen de bounding box van Vlaanderen. Controleer ook of je het Lambert72 coördinatensysteem gebruikt."

Zie ook https://github.com/OnroerendErfgoed/notas/issues/541

https://github.com/OnroerendErfgoed/oe_geoutils/blob/9d6ff12ef91e4c2fe2d75b3e0f8283e8a94e3f67/oe_geoutils/validation/validators_contour.py#L52

**Comment by cahytinne** [comment]
https://github.com/OnroerendErfgoed/notas/commit/753539e04fefa4cd6cbce70e934a80151482ac03
