### ISSUE TITLE
logging verbeteren

### ISSUE THREAD

**Issue by axd1967** [OnroerendErfgoed/oe_geoutils#94]
In https://trac.onroerenderfgoed.be/toepassingen/ticket/2064 wil ik als HH meer informatie over de foutmelding, maar het enige waarover ik beschik is een (soms wazige, vaak onvolledige) foutmelding. Ik zou die Colander foutmelding in een log willen terugvinden zodat ik de gedetailleerde (geo)JSON kan testen.

https://github.com/OnroerendErfgoed/oe_geoutils/blob/633a722dc200fc525eff2959f16af5a0c9fd7da4/oe_geoutils/validation/validators_contour.py#L153

**Comment by Wim-De-Clercq** [comment]
Agree, `LOG.exception(e)` toevoegen voor de raise. Want gans de error en trace van de originele error wordt hier weggesmeten.

Mooier zou zijn `raise colander.Invalid(node, "Geen geldige GeoJson: %s" % cstruct)  from e` maar dat is python3 exclusief zonder echt deftig python2 equivalent.
