### ISSUE TITLE
Verwijderen van requirements bestanden ten voordele van setup.py in help-libraries

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/oe_geoutils#98]
Aangemaakt naar aanleiding van de discussie in https://github.com/OnroerendErfgoed/inventaris/issues/2861. De travis testen falen omdat een oudere versie van pip die travis gebruikt een probleem heeft bij het installeren van het package pyproj versie 2.4.1.

Het instellen van afhankelijke packages bij onze repos gebeurt nu wat door elkaar in setup.py en requirements(-dev).txt. 

In onze toepassingen hebben we voldoende aan enkel de requirements bestanden die via onze fabric scripts worden geïnstalleerd op de servers, en die door de ontwikkelaars kunnen worden gebruikt om hun lokale venv op te zetten. Alle packages opgegeven in setup.py mogen daar weg (lees: indien deze packages nog niet dubbel staan in de requirements bestanden moeten ze naar de requirements bestanden worden verplaatst)

In de help-libraries zoals deze hebben we enkel behoefte aan een opsomming in setup.py. Door middel van de key install_requires geven we aan welke afhankelijkheden er zijn en definiëren we de versies. Wanneer deze help-library wordt geïnstalleerd in 1 van onze toepassingen dan zullen deze packages mee worden geïnstalleerd. De requirements betanden worden hier niet gebruikt en zijn dus overbodig.
Enige nut van de requirements bestanden hier, is dat de ontwikkelaars lokaal hun venv kunnen opzetten. Maar zij kunnen evengoed de packages installeren op basis van de setup.py via `pip install -e` (of `python setup.py develop`?).

**Dit wordt dan de toegepaste werkwijze.**
> - In de toepassingen gebruiken we dan enkel nog requirements.txt bestanden. In de hulp libraries enkel nog setup.py
> - We gebruiken in setup.py van de help-libs de key install_requires om de packages op te geven, waarbij we ook controle over de versies kunnen uitvoeren
> In principe is dit altijd via >= dat bij elke nieuwe release van oe_geouitls wordt opgewaardeerd naar de meest recente versie. Wat betreft het package pyproj specificeren we ook de maximum versie < 2.4.0 tot travis zijn pip versie upgradet

**Nadeel:**
- Telkens als we een nieuwe versie van oe_geoutils moet voor alle afhankelijke packages in setup.py eigenlijk de meeste recente versie als minimum versie worden ingesteld 

**Voordeel:**
- Geen dubbele packages (in setup.py en requirements)
- Steeds de meest recente versie van de afhankelijke packages
- we kunnen problemen zoals hier met pyproj beter opvangen door ook een maximum versie in te stellen in setup.py

**Concrete TODO**
- Verwijder de requirements bestanden
- alle packages uit de requirements bestanden komen in setup.py
- alle packages krijgen een minimum-versie (>=) waarin de meest recente versie wordt ingesteld
- het package pyproj krijgt ook een maximum (2.4.0, minimum mag versie uit requirements.txt zijn) tot travis zijn pip versie opgewaardeerd (probleem is van toepassing bij pip==18.1 en niet meer bij 19.3.1)

@claeyswo @Wim-De-Clercq @koenedaele: Nog opmerkingen?

**Comment by claeyswo** [comment]
Nope, voor onze toepassingen negeren we die setup.py nu ook al dus dat maakt het eigenlijk duidelijker.

**Comment by Wim-De-Clercq** [comment]
`pip install -e .` en `python setup.py develop` zijn wel ongeveer hetzelfde denk ik.
Dit is uit de help command van pip install:
```
  -e, --editable <path/url>   Install a project in editable mode (i.e. setuptools "develop mode") from a local project path or a VCS url.
```
Zolang we vooral `>` doen en weinig `<` zie ik geen problemen. (Het is de combinatie van > en < dat eventueel voor conflicten kan zorgen).


Over mijn ticket bij pyproj zijn ze nog wat aan het discussieren btw: https://github.com/pyproj4/pyproj/issues/477
